#!/bin/sh

# do_diff: compare local copies of config files to their HEAD revisions

diff -qs ~/.toprc other/.toprc
diff -qs ~/.vimrc vim/.vimrc
# how to diff .vim directory?
# how to diff weechat directory?
diff -qs ~/.config/awesome/rc.lua xorg+awesome/rc.lua
diff -qs ~/.Xdefaults xorg+awesome/.Xdefaults
diff -qs ~/.xinitrc xorg+awesome/.xinitrc
diff -qs ~/.zlogin zsh/.zlogin
diff -qs ~/.zshrc zsh/.zshrc
