#!/bin/bash

echo Updating local file system from repo...

set -o verbose

# git config
cp git/.gitignore_core ~
git config --global core.excludesfile '~/.gitignore_core'
cp -R git/.git_template ~
git config --global init.templatedir '~/.git_template'

# vim config
mkdir -p ~/.vim
cp -R vim/.vim ~
cp vim/.vimrc ~/.vim/vimrc
ln -s ~/.vim/vimrc ~/.vimrc

# weechat config
cp -R weechat ~/.weechat

# xorg config
cp xorg+awesome/.Xdefaults ~
cp xorg+awesome/.xinitrc ~

# awesome wm config
mkdir -p ~/.config/awesome
cp -R xorg+awesome/alttab ~/.config/awesome
cp xorg+awesome/rc.lua ~/.config/awesome
cp xorg+awesome/cal.lua ~/.config/awesome
cp xorg+awesome/sysmonitor.lua ~/.config/awesome
cp xorg+awesome/update_notifications.lua ~/.config/awesome

# zsh config
cp zsh/.zlogin ~
cp zsh/.zshrc ~
cp zsh/.zshenv ~

# other config
cp other/.toprc ~

unset -o verbose

echo Done!
echo You will probably need to edit ~/.xinitrc.
