#############################################################################
##`````````````````````````````````````````````````````````````````````````##
##`````````````````````````````ENV VARIABLES```````````````````````````````##
##`````````````````````````````````````````````````````````````````````````##
#############################################################################
export HISTFILE="${ZDOTDIR:-$HOME}/.zhistory"   # The path to the history file.
export HISTSIZE=10000                           # The maximum number of events to save in the internal history.
export SAVEHIST=10000                           # The maximum number of events to save in the history file.
# if a command takes longer than $REPORTTIME seconds to execute, show its execution
# time, formatted according to $TIMEFMT
export REPORTTIME=5
export TIMEFMT="%U user %S system %P cpu %*Es total"
export EDITOR='nvim'
export LANG='en_US.UTF-8'
#export LANGUAGE='en_US.UTF-8'
export LC_ALL='en_US.UTF-8'
# homebrew should come first
#export PATH=$(getconf PATH):/usr/local/bin:$HOME/.local/bin:/usr/bin/core_perl
#export XDG_CONFIG_HOME=$HOME/.config
# see https://askubuntu.com/questions/466198/how-do-i-change-the-color-for-directories-with-ls-in-the-console
#LS_COLORS=$LS_COLORS:'di=1;37:' ; export LS_COLORS
# for zsh syntax highlighting
export ZSH_HIGHLIGHT_HIGHLIGHTERS_DIR=/opt/homebrew/share/zsh-syntax-highlighting/highlighters

# java config
#export JAVA_HOME="/lib/jvm/default"
# for android
#export PATH=$PATH:$HOME/.local/share/android/android-sdk-linux/platform-tools
#export PATH=$PATH:$HOME/.local/share/android/android-sdk-linux/tools
#export ANDROID_EMULATOR_USE_SYSTEM_LIBS=1
#export ANDROID_HOME=$HOME/.local/share/android/android-sdk-linux

# clojure config
# see https://practical.li/clojure/install/clojure-cli/
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:=$HOME/.config}"
export XDG_DATA_HOME="${XDG_DATA_HOME:=$HOME/.local/share}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:=$HOME/.cache}"
#export ZDOTDIR="${ZDOTDIR:=$XDG_CONFIG_HOME/zsh}"

# python config
#export PYTHONPATH="$PYTHONPATH":"$HOME"/.local/lib

# golang config
#export GOPATH=$HOME/.go
#export PATH=$PATH:$GOPATH/bin

# ruby config
export GEM_HOME=$(ruby -e 'print Gem.user_dir')
## homebrew doesn't link ruby by default to avoid conflicts with builtin macos ruby version
export PATH=/opt/homebrew/opt/ruby/bin:$PATH

# ocaml config
#. $HOME/.opam/opam-init/init.zsh > /dev/null 2> /dev/null || true

# haskell config
#export PATH=$PATH:$HOME/.local/stackbin

# rust config
#export PATH=$PATH:$HOME/.cargo/bin

# pass config
export PASSWORD_STORE_CHARACTER_SET='[:alnum:]!@#$%^*()-_+=/";:'

# settings for japanese input
#export GTK_IM_MODULE=ibus
#export QT_IM_MODULE=ibus
#export XMODIFIERS=@im=ibus

# settings for emacspeak
#export DTK_PROGRAM=$(which espeak)

# google cloud SDK config
#export PATH=$PATH:$HOME/.local/share/google-cloud-sdk/bin

# nvm config
export NVM_DIR="$HOME/.nvm"
