# set up displays

# add a new mode with the correct resolution
MODELINE=$(cvt $DUDELSON_CONFIG_MONITOR_RESOLUTION_X $DUDELSON_CONFIG_MONITOR_RESOLUTION_Y | grep Modeline)
NEW_MODE=$(echo $MODELINE | awk '{ print $2 }')
xrandr --newmode $(echo $MODELINE | cut -d " " -f 2-)

# add the display mode for each monitor
for i in $(seq 0 $((DUDELSON_CONFIG_N_MONITORS - 1))); do
    xrandr --addmode $(eval echo \$DUDELSON_CONFIG_MONITOR_$i) $NEW_MODE
done

# lay out the monitors relative to each other
for i in $(seq 0 $((DUDELSON_CONFIG_N_MONITORS - 1))); do
    if [ $i = "0" ]; then
        xrandr --output $(eval echo \$DUDELSON_CONFIG_MONITOR_$i) --mode $NEW_MODE --primary
    else
        # no --left-of or --right-of options are needed here since we enumerate
        # over the monitors in left-to-right order, and xorg automatically orders
        # monitors from left to right, starting with the primary
        xrandr --output $(eval echo \$DUDELSON_CONFIG_MONITOR_$i) --mode $NEW_MODE
    fi
done

# start services

xbindkeys

if [ $DUDELSON_CONFIG_ENABLE_JAPANESE_IME = "1" ]; then
    # start fcitx (japanese input)
    # note that there's no need to check if the daemon is already running. The -r
    # option does this for us
    ibus-daemon -drx
fi

if [ $DUDELSON_CONFIG_SWAP_CAPS_CTRL = "1" ]; then
    # swap caps lock and left ctrl
    setxkbmap -option "ctrl:swapcaps"
fi

if [ $DUDELSON_CONFIG_ENABLE_COMPOSITING = "1" ]; then
    # start compositing manager
    compton &
fi


# run machine-specific configuration
~/.xinitrc-user

# start awesome
exec awesome &>> $AWESOME_LOG_FILE
