[window]
opacity = 0.8
blur = true
startup_mode = "Maximized"
padding = { x = 6, y = 6 }

[font]
normal = { family = "SauceCodePro Nerd Font Mono", style = "Regular" }
#bold = { style = "Bold" }
#italic = { style = "Italic" }
#bold_italic = { style = "Bold Italic" }
size = 14.0
